export const OVERDUE_REDUX_CONSTANTS = {
  GET_OVERDUE_LIST: 'GET_OVERDUE_LIST',
  GET_ENTITY_LIST: 'GET_ENTITY_LIST',
  RESET_OVERDUE_LIST_PAGINATION_DATA: 'RESET_OVERDUE_LIST_PAGINATION_DATA',

  GET_OVERDUE_ENTITY_DATA_BY_SEARCH: 'GET_OVERDUE_ENTITY_DATA_BY_SEARCH',

  OVERDUE_CRUD_CONSTANTS: {
    UPDATE_OVERDUE_LIST_AFTER_AMEND: 'UPDATE_OVERDUE_LIST_AFTER_AMEND',
    UPDATE_OVERDUE_LIST_AFTER_ADD: 'UPDATE_OVERDUE_LIST_AFTER_ADD',
    CHANGE_OVERDUE_DETAILS_ACTION: 'CHANGE_OVERDUE_DETAILS_ACTION',
    GET_OVERDUE_DETAILS: 'GET_OVERDUE_DETAILS',
    GET_OVERDUE_LIST_BY_DATE: 'GET_OVERDUE_LIST_BY_DATE',
    COPY_OVERDUE_LIST_BY_DATE: 'COPY_OVERDUE_LIST_BY_DATE',
    UPDATE_OVERDUE_LIST_BY_DATE: 'UPDATE_OVERDUE_LIST_BY_DATE',
    UPDATE_COPY_OVERDUE_LIST_BY_DATE: 'UPDATE_COPY_OVERDUE_LIST_BY_DATE',
    CHANGE_OVERDUE_FIELD_VALUE: 'CHANGE_OVERDUE_FIELD_VALUE',
    RESET_OVERDUE_FORM_DATA: 'RESET_OVERDUE_FORM_DATA',
  },
  IMPORT_OVERDUE: {
    GO_TO_NEXT_STEP: 'GO_TO_NEXT_STEP',
    SET_FILE: 'SET_FILE',
    DELETE_IMPORTED_FILE: 'DELETE_IMPORTED_FILE',
    UPDATE_DATA_ERROR: 'UPDATE_DATA_ERROR',
    UPDATE_DATA_ON_SUCCESS: 'UPDATE_DATA_ON_SUCCESS',
    RESET_STEPPER_DATA: 'RESET_STEPPER_DATA',
  },
};
